# yaml-language-server: $schema=labels.schema.json
---
labels:
  - name: bug
    color: "#d73a4a"
    description: Something isn't working

  - name: feature
    color: "#a2eeef"
    description: New feature or meaningful behavior change
    aliases: [enhancement]

  - name: docs
    color: "#0075ca"
    description: Improvements or additions to documentation and learning materials
    aliases: [documentation]

  - name: question
    color: "#d876e3"
    description: Further information is requested

  - name: duplicate
    color: "#cfd3d7"
    description: This issue or pull request already exists

  - name: invalid
    color: "#e4e669"
    description: This doesn't seem right

  - name: wontfix
    color: "#ffffff"
    description: This will not be worked on

  - name: good first issue
    color: "#7057ff"
    description: Good for newcomers

  - name: help wanted
    color: "#008672"
    description: Extra attention is needed

  - name: refactor
    color: "#c2e0c6"
    description: Internal code cleanup with no behavior change

  - name: perf
    color: "#fef2c0"
    description: Performance or memory improvements

  - name: chore
    color: "#c5def5"
    description: Tooling, CI, or configuration changes

  - name: "P0: critical"
    color: "#b60205"
    description: Broken core flows, must fix ASAP

  - name: "P1: high"
    color: "#d93f0b"
    description: High-impact issues with workarounds

  - name: "P2: normal"
    color: "#fbca04"
    description: Standard priority work

  - name: "P3: low"
    color: "#0e8a16"
    description: Nice-to-have, polish, or low impact

  - name: "area: ci"
    color: "#006b75"
    description: GitHub Actions, workflows, and automation

  - name: "area: cli"
    color: "#1d76db"
    description: CLI arguments, flags, and console output

  - name: "area: core"
    color: "#5319e7"
    description: Core logic, config parsing, and synchronization

  - name: "area: pkg"
    color: "#f9d0c4"
    description: Packaging, NPM/JSR publishing, and distribution

  - name: test
    color: "#90EE90"
    description: Tests and testing utilities

  - name: test-summary
    color: "#ededed"
    description: Label for testing GitHub Action step summary

  - name: blocked
    color: "#bdb76b"
    description: Work cannot proceed due to an external dependency

# Clean up old area labels that were replaced by area: prefixed versions
delete:
  - core-vm
  - ui
  - labs
  - content
