name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "Breaking Changes"
    labels:
      - breaking
      - breaking-change
  - title: "New Features"
    labels:
      - feature
      - enhancement
  - title: "Bug Fixes"
    labels:
      - bug
      - fix
  - title: "Documentation"
    labels:
      - docs
      - documentation
  - title: "Maintenance"
    labels:
      - chore
      - maintenance
      - dependencies

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - breaking
      - breaking-change
  minor:
    labels:
      - feature
      - enhancement
  patch:
    labels:
      - bug
      - fix
      - chore
      - docs
  default: patch

template: |
  ## Changes

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
