name: github-labelmanager
description: Manage GitHub labels
author: Kaj Kowalski

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
    REPO: ${{ inputs.repository }}
    DRY_RUN: ${{ inputs.dry-run }}
    CONFIG_PATH: ${{ inputs.config-path }}

inputs:
  token:
    description: "GitHub Personal Access Token (must have issues: write permission)"
    required: true
    default: ${{ github.token }}
  repository:
    description: Repository in 'owner/repo' format
    required: true
    default: ${{ github.repository }}
  dry-run:
    description: Run without making changes to GitHub
    required: false
    default: false
  config-path:
    description: Path to the configuration file
    required: true
    default: .github/labels.yml
