name: Validate Release Version
description: Extract and validate version from deno.json against git tag

inputs:
  event-name:
    description: GitHub event name (push or pull_request)
    required: false
    default: ${{ github.event_name }}
  ref-name:
    description: Git ref name (tag name for push events)
    required: false
    default: ${{ github.ref_name }}

outputs:
  version:
    description: Validated version string (e.g. v1.2.3)
    value: ${{ steps.validate.outputs.version }}
  is_tag:
    description: Whether this is a tag push (not a PR)
    value: ${{ steps.validate.outputs.is_tag }}
  prerelease:
    description: Whether this is a prerelease version
    value: ${{ steps.validate.outputs.prerelease }}
  is_stable:
    description: Whether this is a stable tag release (is_tag && !prerelease)
    value: ${{ steps.validate.outputs.is_stable }}
  mode:
    description: Mode string - publish for tag pushes, dry-run for PRs
    value: ${{ steps.validate.outputs.mode }}

runs:
  using: composite
  steps:
    - name: Validate version
      id: validate
      shell: bash
      run: ${{ github.action_path }}/validate.sh
      env:
        EVENT_NAME: ${{ inputs.event-name }}
        REF_NAME: ${{ inputs.ref-name }}
