name: Check schema is up-to-date
description: |
  Generates schema and checks for changes via git diff.
  Requires: deno in PATH, git checkout with tracked schema file.

outputs:
  outdated:
    description: Whether schema is outdated
    value: ${{ steps.schema.outputs.outdated }}
  up-to-date:
    description: Whether schema is up-to-date
    value: ${{ !fromJSON(steps.schema.outputs.outdated) }}

inputs:
  file:
    description: File to check
    default: .github/labels.schema.json
    required: true

runs:
  using: composite
  steps:
    - name: Check schema is up-to-date
      id: schema
      uses: actions/github-script@v8
      env:
        SCHEMA_FILE: ${{ inputs.file }}
      with:
        script: |
          const schemafile = process.env.SCHEMA_FILE;

          await exec.exec('deno', ['task', 'schema']);

          // Destructuring the result (cleaner syntax)
          const { exitCode, stdout } = await exec.getExecOutput(
            'git',
            ['diff', '--color=never', schemafile],
            { ignoreReturnCode: true }
          );

          if (exitCode === 0) {
            core.summary.addHeading(':white_check_mark: Schema is up-to-date', 3);
            core.setOutput('outdated', 'false'); // standardized on 'outdated'
          } else {
            core.summary.addHeading(':x: Schema is out-of-date', 3);
            core.summary.addRaw('The schema file has changed. Please run the updater locally.');
            core.summary.addRaw(`\n\n**File:** \`${schemafile}\`\n`);

            core.summary.addCodeBlock(stdout, 'diff');

            core.summary.addRaw('\n> **Run `deno task schema` locally to update.**\n');

            core.setOutput('outdated', 'true');
            core.setFailed('Schema needs update');
          }

          await core.summary.write();
