name: Release Drafter

on:
  push:
    branches: [master]
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
